"""Initial migration.

Revision ID: 0d2cc0fd3b34
Revises: 
Create Date: 2024-10-16 22:57:30.477645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d2cc0fd3b34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution_event', sa.JSON(), nullable=True))
        batch_op.alter_column('contribution_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('contributioni_event')

    with op.batch_alter_table('Fees', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('Households', schema=None) as batch_op:
        batch_op.alter_column('apartment_number',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('Residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('Residents', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('Households', schema=None) as batch_op:
        batch_op.alter_column('apartment_number',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('Fees', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('Contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contributioni_event', mysql.JSON(), nullable=True))
        batch_op.alter_column('contribution_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('contribution_event')

    # ### end Alembic commands ###
