"""Initial migration.

Revision ID: 168f6dcb66f6
Revises: b7bfbea4a1b7
Create Date: 2024-10-18 00:29:04.879144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '168f6dcb66f6'
down_revision = 'b7bfbea4a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['user_id'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint('Users_ibfk_1', type_='foreignkey')
        batch_op.drop_column('resident_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resident_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Users_ibfk_1', 'Residents', ['resident_id'], ['resident_id'])

    with op.batch_alter_table('Residents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
