"""Initial migration.

Revision ID: 548a631e382f
Revises: a99190686a38
Create Date: 2024-10-16 23:05:56.458886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '548a631e382f'
down_revision = 'a99190686a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('Tạm trú', 'Tạm vắng', 'Thường trú'), nullable=True))
        batch_op.drop_column('temporary_residence')
        batch_op.drop_column('temporary_absence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_absence', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('temporary_residence', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
