"""Initial migration.

Revision ID: b7bfbea4a1b7
Revises: 893e8e520ecf
Create Date: 2024-10-18 00:27:14.298986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7bfbea4a1b7'
down_revision = '893e8e520ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Households', schema=None) as batch_op:
        batch_op.drop_constraint('Households_ibfk_2', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resident_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'Residents', ['resident_id'], ['resident_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resident_id')

    with op.batch_alter_table('Households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Households_ibfk_2', 'Users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
